name: mobile
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shimmer: ^3.0.0
  cupertino_icons: ^1.0.5
  http: ^1.1.1
  path: ^1.9.1
  path_provider: ^2.1.5
  image_picker: ^1.0.7
  image: ^4.5.4
  image_cropper: ^8.0.0
  file_picker: ^8.0.3
  url_launcher: ^6.3.0
  google_fonts: ^6.2.1
  dio: ^5.6.0
  open_filex: ^4.4.0
  audioplayers: ^6.5.1
  overlay_support: ^2.1.0

  # إشعارات + التوقيت (تم حل التعارض برفع الإشعارات)
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1

  # تخزين آمن + تنسيق وقت/تاريخ
  flutter_secure_storage: ^9.0.0
  timeago: ^3.6.0
  intl: ^0.19.0

  # Firebase
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.0
  fl_chart: ^0.66.2
  table_calendar: ^3.0.9
  tutorial_coach_mark: ^1.3.3
  shared_preferences: ^2.5.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/signup_illustration.png
    - assets/images/uniserve_logo.jpeg
    - assets/sounds/message_alert.mp3
    - assets/images/reqbackground.jpg

  fonts:
    - family: Baloo
      fonts:
        - asset: assets/fonts/Baloo2.ttf

    - family: PoiretOne
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
